VERSION="2.6.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GCO3VC5VN4F6KKH2HZTXKSY2CSQVGVVYWJLC5AUOS7GFQ4E2VTZCOTFH",
"GAPJTZXQK5TPMBLSGRLMMWGUUI2C7QIQ7NQM3EDU5I5C3TL3W37I3XCL", 
"GASWHVJOVHIQR4YBVQ2RE3PTGT7VKO7NIX6K4HT6SFMHWU7IGP6WUAYG"
]

[DOCUMENTATION]
ORG_NAME="JET"
ORG_URL="https://jet.my.id"
ORG_LOGO="https://jet.my.id/jet.png"

[[CURRENCIES]]
code="JETON"
issuer="GASWHVJOVHIQR4YBVQ2RE3PTGT7VKO7NIX6K4HT6SFMHWU7IGP6WUAYG"
name="JET Token"
desc="JETON is a utility token that powers the JET Platform, a platform for creating, sharing, and trading meme tokens on the Stellar blockchain. JETON is an integral part of the platform's ecosystem, providing users with various benefits and functionalities."
image="https://jet.my.id/jetonlogo.png"
display_decimals=2
is_asset_anchored=false
fixed_number=100000000
conditions="There will only ever be 100,000,000 JETON tokens in existence."

[[CURRENCIES]]
code="EDOGE"
issuer="GCO3VC5VN4F6KKH2HZTXKSY2CSQVGVVYWJLC5AUOS7GFQ4E2VTZCOTFH"
name="Eternity Doge"
desc="Eternity Doge (EDOGE) token is a meme token that celebrates dogs, the loyal companions of humans for centuries. Eternity Doge Token is meant to represent the eternal bond between humans and their canine friends."
image="https://jet.my.id/edogelogo.png"
display_decimals=2
is_asset_anchored=false
fixed_number=500000000000
conditions="There will only ever be 500,000,000,000 EDOGE tokens in existence."

[[CURRENCIES]]
code="KINTA"
issuer="GAPJTZXQK5TPMBLSGRLMMWGUUI2C7QIQ7NQM3EDU5I5C3TL3W37I3XCL"
name="Kintamani"
desc="Woof woof! Get ready to unleash the power of the Kintamani, Bali's iconic dog breed, with the $KINTA meme token! $KINTA is more than just a cute face on a coin. We're building a community of dog lovers, meme enthusiasts, and crypto adventurers who appreciate the unique spirit of the Kintamani."
image="https://jet.my.id/kintamani.png"
display_decimals=2
is_asset_anchored=false
fixed_number=100000000000
conditions="There will only ever be 100,000,000,000 KINTA tokens in existence."
