VERSION="2.6.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"


ACCOUNTS=[
"GCO3VC5VN4F6KKH2HZTXKSY2CSQVGVVYWJLC5AUOS7GFQ4E2VTZCOTFH",
]

[[CURRENCIES]]
code="EDOGE"
issuer="GCO3VC5VN4F6KKH2HZTXKSY2CSQVGVVYWJLC5AUOS7GFQ4E2VTZCOTFH"
name="Eternity Doge"
desc="Eternity Doge (EDOGE) token is a meme token that celebrates dogs, the loyal companions of humans for centuries. Eternity Doge Token is meant to represent the eternal bond between humans and their canine friends."
image="https://ipfs.io/ipfs/bafkreifdv3gimixro4ijxqn6zacwzr6oej22px34kuj23uvw6p22hqv6z4"
display_decimals=2
is_asset_anchored=false
fixed_number=500000000000
conditions="There will only ever be 500,000,000,000 EDOGE tokens in existence."
